import type { IndustryPage } from "@/lib/types";

export const industries: IndustryPage[] = [
  {
    slug: "/industries/bfsi",
    name: "BFSI & Fintech",
    group: "Regulated",
    scenarios: [
      { moment: "Login and payment OTP", detail: "A one-time code that has to land in seconds, regardless of network conditions, to authorise a transaction." },
      { moment: "Loan EMI due reminder", detail: "A nudge before the due date with the amount, the loan reference and a pay-now link." },
      { moment: "Suspicious transaction alert", detail: "An immediate alert naming the amount, the last four digits of the account, and a number to call if it wasn't the customer." },
      { moment: "KYC document reminder", detail: "A follow-up asking a customer to upload a pending document before their account is restricted." },
    ],
    channelMix: [
      { moment: "Login OTP", channel: "SMS, with Voice fallback", why: "Speed and reliability matter more than richness for a security code." },
      { moment: "EMI due reminder", channel: "WhatsApp", why: "Supports a quick-reply button and a pay-now link in one message." },
      { moment: "Suspicious transaction alert", channel: "SMS", why: "Fastest channel, works on any handset, no read-receipt dependency." },
      { moment: "KYC reminder", channel: "WhatsApp", why: "Can carry a document-upload link and a short explainer." },
    ],
    complianceNotes: [
      "OTP and transaction alerts must run on a transactional route, never a promotional one, or they get blocked outright rather than merely delayed.",
      "Time-sensitive headers — fraud alerts, loan disbursal — need explicit category tagging at template registration, or they queue behind ordinary marketing traffic.",
      "Consent records for EMI and collections messages should be kept on file, since these sit close to the DND boundary even though they are service messages.",
      "Content implying guaranteed returns or specific transaction values is a common rejection reason at template review — draft around it rather than after a rejection.",
    ],
    templatePack: [
      { title: "Login / transaction OTP", body: "{{1}} is your OTP to complete your transaction on {{2}}. Valid for {{3}} minutes. Do not share this code with anyone." },
      { title: "EMI due reminder", body: "Hi {{1}}, your EMI of ₹{{2}} for loan {{3}} is due on {{4}}. Pay now: {{5}}" },
      { title: "Suspicious transaction alert", body: "Alert: A transaction of ₹{{1}} was made on your account ending {{2}} at {{3}}. If this wasn't you, call {{4}} immediately." },
      { title: "KYC reminder", body: "{{1}}, your KYC update is pending. Upload documents here: {{2}} to avoid account restriction." },
    ],
    integrations: [
      "Core banking systems, connected over a secure webhook",
      "Loan origination and collections software",
      "CRM systems such as Salesforce and Zoho",
      "Fraud and risk-monitoring systems for real-time alert triggers",
    ],
    faq: [
      { q: "Which SMS route should banks use for OTP and transaction alerts?", a: "Both belong on a transactional route, never a promotional one. A promotional route is DND-scrubbed and throttled, so an OTP or a fraud alert sent that way can be blocked or delayed rather than delivered in seconds. Register the OTP and alert templates under the service or transactional category at DLT so they bypass DND and marketing-window rules." },
      { q: "Can we send EMI and collections reminders without breaching DND rules?", a: "Yes, if the reminder is tied to an existing loan account and drafted as a service message rather than an offer. These sit close to the DND boundary, so keep consent records on file and avoid promotional wording. A pay-now nudge on WhatsApp works well because it carries a button and a payment link, but the recipient must have opted in to WhatsApp first." },
      { q: "Why do our OTP templates keep getting rejected at DLT approval?", a: "The usual causes are wording that implies a guaranteed return or a specific transaction value, an undeclared URL, or the wrong template category. Declare every variable and link at registration, keep the OTP template to code, validity and a do-not-share line, and register it under the correct transactional category before you rely on it going live." },
      { q: "Is WhatsApp suitable for suspicious-transaction alerts?", a: "For the fastest fraud alert, SMS is safer: it reaches any handset instantly with no read-receipt or app dependency. WhatsApp suits richer, less time-critical messages such as KYC document uploads or EMI reminders, where a link and a quick-reply button add value and a short delay is acceptable." },
    ],
    relatedSolutions: ["/solutions/otp-verification", "/solutions/payment-reminders", "/solutions/alerts"],
  },
  {
    slug: "/industries/healthcare",
    name: "Healthcare",
    group: "Regulated",
    scenarios: [
      { moment: "Appointment reminder", detail: "A confirmation with the doctor's name, time, and a one-tap reschedule option." },
      { moment: "Report ready", detail: "A notice that a test report is available, without naming the test or the result." },
      { moment: "Prescription refill reminder", detail: "A nudge when a recurring prescription is due, with a reply-to-reorder option." },
      { moment: "Emergency or outbreak alert", detail: "A same-day advisory sent to patients or residents in a defined area." },
    ],
    channelMix: [
      { moment: "Appointment reminder", channel: "WhatsApp, with SMS fallback", why: "A reschedule link and read confirmation help cut no-shows." },
      { moment: "Report ready", channel: "SMS", why: "No clinical detail sits in the message — just a notice and a secure link." },
      { moment: "Prescription refill", channel: "WhatsApp", why: "A quick-reply button turns a reminder into a reorder in one tap." },
      { moment: "Emergency alert", channel: "Voice broadcast", why: "Reaches patients who won't open an app, including older or low-literacy patients." },
    ],
    complianceNotes: [
      "No clinical or diagnosis detail belongs in a promotional-route template — reports are referenced only as \"ready\", with a secure link, never named tests or values.",
      "Consent for appointment reminders and consent for marketing messages are recorded separately, since anything health-adjacent draws closer scrutiny at template approval.",
      "The service-versus-promotional template category determines whether health-specific wording is permitted at all — draft to the stricter service category by default.",
      "Outbreak or public-health alerts sent at volume need pre-approval as public-interest content, not standard promotional templates.",
    ],
    templatePack: [
      { title: "Appointment reminder", body: "Hi {{1}}, your appointment with Dr. {{2}} is confirmed for {{3}} at {{4}}. Reply CONFIRM or call {{5}} to reschedule." },
      { title: "Report ready", body: "{{1}}, your test report is ready. View or download it here: {{2}}. For queries, contact {{3}}." },
      { title: "Prescription refill", body: "Hi {{1}}, your prescription for {{2}} is due for refill. Reply YES to reorder or visit {{3}}." },
      { title: "Emergency alert", body: "Public health alert for {{1}} residents: {{2}}. For guidance, call {{3}}." },
    ],
    integrations: [
      "Hospital HIS and EMR systems, connected over a webhook",
      "Appointment-scheduling software",
      "Lab information systems (LIS)",
      "Pharmacy management systems",
    ],
    faq: [
      { q: "Can we send appointment reminders without revealing patient details?", a: "Yes. A reminder should carry only the doctor's name, date and time, plus a reschedule option, and no diagnosis or reason for the visit. WhatsApp works well here with an SMS fallback because it supports a reschedule link and a read confirmation, which helps cut no-shows without exposing anything clinical in the message body." },
      { q: "How do we notify patients that a test report is ready?", a: "Send a plain notice that the report is available with a secure link to view it, never the test name, values or result in the message. Report-ready notices go out on an SMS transactional route so they land without an app, and the clinical detail stays behind the secure portal login rather than in the template." },
      { q: "Is health-related content allowed in DLT and WhatsApp templates?", a: "Anything health-adjacent draws closer scrutiny at template approval, so draft to the stricter service category by default and keep clinical wording out of the body. Record consent for appointment reminders separately from marketing consent. Bulk outbreak or public-health advisories need pre-approval as public-interest content rather than standard promotional templates." },
      { q: "What is the best channel for an emergency or outbreak alert?", a: "A Voice broadcast, often alongside SMS, gives the widest reach in a genuine public-health situation because it reaches patients who will not open an app, including older or low-literacy patients. At volume these advisories need clearance as public-interest content, not a standard promotional send." },
    ],
    relatedSolutions: ["/solutions/appointments", "/solutions/alerts", "/solutions/support"],
  },
  {
    slug: "/industries/insurance",
    name: "Insurance",
    group: "Regulated",
    scenarios: [
      { moment: "Premium due reminder", detail: "A payment nudge naming the policy number, the amount, and a pay-now link." },
      { moment: "Policy renewal", detail: "A notice ahead of expiry with the renewal document and a one-tap renew option." },
      { moment: "Claim status update", detail: "A short, factual update on where a claim stands, without stating settlement amounts." },
      { moment: "Welcome after purchase", detail: "Confirmation that a policy is active, with the policy document attached." },
    ],
    channelMix: [
      { moment: "Premium due", channel: "SMS and WhatsApp", why: "WhatsApp for the pay-now button; SMS covers policyholders without the app installed." },
      { moment: "Renewal", channel: "WhatsApp", why: "Carries the renewal document and a pay-now button in one message." },
      { moment: "Claim status", channel: "SMS", why: "A short factual update that needs no login to read." },
      { moment: "Onboarding", channel: "WhatsApp", why: "Delivers the policy document and hands off to a support bot for questions." },
    ],
    complianceNotes: [
      "Premium and renewal reminders are drafted as service messages tied to an existing policy number, not general marketing — that distinction decides which route they can run on.",
      "Claim-status updates should avoid stating settlement amounts or medical or accident detail in the template — link out to a secure portal instead.",
      "Cross-sell nudges, such as a top-up cover offer, count as promotional and need a DND-scrubbed route with consent on file, even for an existing policyholder.",
      "Any URL sent inside a template — static or dynamic per policyholder — has to be declared as such at registration, or the template gets rejected.",
    ],
    templatePack: [
      { title: "Premium due", body: "{{1}}, your premium of ₹{{2}} for policy {{3}} is due on {{4}}. Pay now: {{5}}" },
      { title: "Renewal", body: "Hi {{1}}, your policy {{2}} is up for renewal on {{3}}. Renew here: {{4}}" },
      { title: "Claim status", body: "Update on claim {{1}}: status changed to {{2}}. Details: {{3}}" },
      { title: "Onboarding", body: "Welcome {{1}}! Your policy {{2}} is now active. Download your policy document: {{3}}" },
    ],
    integrations: [
      "Policy administration systems",
      "Claims management software",
      "CRM and agent-distribution platforms",
      "Payment gateways for premium collection",
    ],
    faq: [
      { q: "Are premium and renewal reminders treated as service or promotional messages?", a: "When they reference an existing policy number and a due date, they are service messages and can run on a transactional route. A cross-sell nudge such as a top-up cover offer is promotional, so it needs a DND-scrubbed route with consent on file even for a current policyholder. That distinction decides which route each template can use." },
      { q: "How should we word a claim-status update?", a: "Keep it factual and short: the claim reference and the new status, with a link to a secure portal for the rest. Avoid stating settlement amounts or any medical or accident detail in the template itself, both because it invites template rejection and because it exposes sensitive information over SMS. SMS suits these because they need no login to read the headline." },
      { q: "Can we send the policy document over WhatsApp?", a: "Yes. WhatsApp can carry the policy document as an attachment in an onboarding or renewal message, which is why it suits welcome and renewal moments where a pay-now button and the document belong together. SMS remains the fallback for policyholders who have not installed WhatsApp or opted in." },
      { q: "Do we need to declare payment links inside insurance templates?", a: "Yes. Any URL inside a template, whether a fixed link or one that changes per policyholder, has to be declared at registration, and a per-policyholder link needs the dynamic-URL template category. Undeclared links are a common rejection reason at template review." },
    ],
    relatedSolutions: ["/solutions/payment-reminders", "/solutions/alerts", "/solutions/support"],
  },
  {
    slug: "/industries/government",
    name: "Government & Public Sector",
    group: "Regulated",
    scenarios: [
      { moment: "Scheme enrolment confirmation", detail: "A confirmation with a reference ID after a citizen enrols in a scheme." },
      { moment: "Subsidy or benefit disbursal alert", detail: "A notice that a benefit amount has been credited, and where." },
      { moment: "Public advisory", detail: "A same-day notice sent widely — a weather warning, a service disruption, a public-health notice." },
      { moment: "Grievance status update", detail: "A short update on where a filed complaint or ticket stands." },
    ],
    channelMix: [
      { moment: "Enrolment confirmation", channel: "SMS", why: "Reaches feature phones across every district, not just smartphone users." },
      { moment: "Disbursal alert", channel: "SMS, with Voice for wide reach", why: "Voice covers residents with lower literacy or smaller screens." },
      { moment: "Public advisory", channel: "Voice broadcast and SMS", why: "The widest possible reach in a genuine emergency." },
      { moment: "Grievance status", channel: "SMS", why: "Concise and has no dependency on installing an app." },
    ],
    complianceNotes: [
      "Entity registration for a government department or public-sector undertaking typically follows its own registration category, with its own approval chain and timeline.",
      "Bulk public advisories need pre-approval as public-interest content — they don't move through the same throttling and DND rules as commercial promotional sends.",
      "Multi-lingual content, often a requirement in public communication, changes segment count and needs testing for correct rendering in each regional script before a mass send.",
      "Beneficiary data used to trigger disbursal alerts stays under the department's own data-handling process; MsgBridge's role is limited to delivering the message.",
    ],
    templatePack: [
      { title: "Enrolment confirmation", body: "{{1}}, your enrolment for {{2}} scheme is confirmed. Reference ID: {{3}}." },
      { title: "Disbursal alert", body: "₹{{1}} has been credited to your registered account under {{2}} scheme on {{3}}." },
      { title: "Public advisory", body: "Advisory from {{1}}: {{2}}. For more information call {{3}}." },
      { title: "Grievance update", body: "Your grievance {{1}} status: {{2}}. Track at {{3}}." },
    ],
    integrations: [
      "Departmental case-management and grievance-redressal systems",
      "Direct benefit transfer databases, via secure batch upload",
      "e-Governance portals",
      "Citizen helpline and call-centre software",
    ],
    faq: [
      { q: "How does a government department register to send SMS?", a: "A department or public-sector undertaking usually registers under its own entity category on the DLT platform, which carries its own approval chain and timeline separate from commercial senders. Templates for enrolment, disbursal and grievance updates are registered as service or transactional content so they reach citizens on feature phones across every district." },
      { q: "Can we send a public advisory to everyone in a district at once?", a: "Yes, but a bulk public advisory needs pre-approval as public-interest content. It does not move through the same throttling and DND rules as a commercial promotional send. For a genuine emergency, a Voice broadcast alongside SMS gives the widest reach, including residents with lower literacy or basic handsets." },
      { q: "How are regional languages handled in citizen messaging?", a: "Multi-lingual content is often a requirement in public communication. Each language needs its own approved template, and any non-Latin script is sent as Unicode, which changes the SMS segment count. Test each regional script for correct rendering before a mass send so characters do not break mid-message." },
      { q: "Who is responsible for the beneficiary data behind disbursal alerts?", a: "The department. Beneficiary data used to trigger a subsidy or benefit alert stays under the department's own data-handling process. MsgBridge's role is limited to delivering the message from the data the department supplies, typically over a secure batch upload or webhook." },
    ],
    relatedSolutions: ["/solutions/alerts", "/solutions/support", "/solutions/otp-verification"],
  },
  {
    slug: "/industries/ecommerce",
    name: "E-commerce & D2C",
    group: "High volume",
    scenarios: [
      { moment: "Order confirmation", detail: "An immediate confirmation with the order summary and amount." },
      { moment: "Shipping / out-for-delivery update", detail: "A notice when the order ships, and again when it's out for delivery." },
      { moment: "Abandoned cart nudge", detail: "A reminder with the product and a direct checkout link." },
      { moment: "COD payment confirmation", detail: "A confirmation call or message before a cash-on-delivery attempt is made." },
    ],
    channelMix: [
      { moment: "Order confirmation", channel: "WhatsApp", why: "Carries the invoice and order summary in one template." },
      { moment: "Shipping update", channel: "SMS and WhatsApp", why: "SMS as a fallback for customers who haven't opted into WhatsApp." },
      { moment: "Abandoned cart", channel: "WhatsApp", why: "Richer format — a product image and a direct checkout link." },
      { moment: "COD confirmation", channel: "Voice or SMS", why: "Confirms the order before a delivery attempt is made, cutting failed deliveries." },
    ],
    complianceNotes: [
      "Abandoned-cart and other promotional nudges must run on DND-scrubbed routes and respect TRAI's permitted send-time windows — a common rejection reason for late-evening campaigns.",
      "Order and shipping updates are transactional and must map to a genuine triggered event; reusing the same template for marketing content gets it re-classified and blocked.",
      "COD-confirmation messages sent at meaningful volume need a recorded opt-in, since customers can flag unexpected calls or texts as unsolicited.",
      "Regional-language promotional content, common for tier-2 and tier-3 reach, changes the Unicode segment count — a frequent source of billing surprises if not planned for.",
    ],
    templatePack: [
      { title: "Order confirmation", body: "Hi {{1}}, your order #{{2}} for ₹{{3}} is confirmed. Estimated delivery: {{4}}." },
      { title: "Shipping update", body: "Your order #{{1}} has shipped and is out for delivery. Track: {{2}}" },
      { title: "Abandoned cart", body: "{{1}}, you left {{2}} in your cart. Complete your order: {{3}}" },
      { title: "COD confirmation", body: "Please confirm your COD order #{{1}} worth ₹{{2}}. Reply YES to confirm delivery." },
    ],
    integrations: [
      "Shopify, WooCommerce and Magento storefronts",
      "Order management systems (OMS)",
      "Logistics and courier partner APIs",
      "CRM and marketing-automation tools",
    ],
    faq: [
      { q: "How do order and delivery notifications work across SMS and WhatsApp?", a: "Order and shipping updates are transactional and fire from a genuine triggered event, so they run on a transactional route. WhatsApp suits the order confirmation because it can carry the invoice and summary in one template, while SMS is the reliable fallback for shipping updates when a customer has not opted in to WhatsApp. Reusing an order template for marketing gets it re-classified and blocked." },
      { q: "Are abandoned-cart reminders allowed under TRAI rules?", a: "Yes, but they are promotional. They must run on a DND-scrubbed route and respect TRAI's permitted send-time windows, which is why late-evening campaigns are a common rejection or block. WhatsApp works well for cart nudges because it can show a product image and a direct checkout link, provided the customer opted in." },
      { q: "Can we confirm COD orders before dispatch?", a: "Yes. A COD-confirmation message or Voice call before the delivery attempt cuts failed deliveries. At meaningful volume these need a recorded opt-in, since a customer can flag an unexpected call or text as unsolicited. A short reply-YES SMS or a quick automated voice call both work for confirming intent." },
      { q: "Does sending in regional languages change our messaging cost?", a: "It can. Regional-language content is sent as Unicode, which shortens each SMS segment and so raises the segment count for the same message length. For tier-2 and tier-3 reach this is worth planning for up front, since it is a frequent source of billing surprises." },
    ],
    relatedSolutions: ["/solutions/order-updates", "/solutions/marketing", "/solutions/commerce"],
  },
  {
    slug: "/industries/logistics",
    name: "Logistics & Delivery",
    group: "High volume",
    scenarios: [
      { moment: "Pickup confirmed", detail: "A notice the moment a shipment is picked up." },
      { moment: "Out for delivery", detail: "A same-day notice with a live tracking link." },
      { moment: "Failed delivery attempt", detail: "A notice explaining a missed delivery, with a reschedule option." },
      { moment: "COD reminder", detail: "A reminder to keep cash ready before the rider arrives." },
    ],
    channelMix: [
      { moment: "Pickup confirmed", channel: "SMS", why: "Immediate, and needs no app at the pickup point." },
      { moment: "Out for delivery", channel: "WhatsApp", why: "Carries a live-location link and the delivery partner's contact in one template." },
      { moment: "Failed attempt", channel: "SMS, with Voice for reschedule", why: "A voice call for the reschedule when the SMS goes unread." },
      { moment: "COD reminder", channel: "Voice", why: "Confirms cash-in-hand before the rider is already at the door." },
    ],
    complianceNotes: [
      "Each stage of a shipment's lifecycle needs its own approved template — bundling every update into one generic template is a common rejection reason.",
      "Failed-delivery and reschedule messages need the underlying delivery attempt logged and available on request, or high-frequency sends can get flagged.",
      "Voice broadcasts used for COD confirmation at scale need their own registered use case — routing them through an OTP-category voice line gets flagged.",
      "Regional-language delivery updates, a real need outside metro areas, use Unicode encoding and split into more SMS segments, so plan message length for non-Latin scripts upfront.",
    ],
    templatePack: [
      { title: "Pickup confirmed", body: "Your shipment #{{1}} has been picked up and is on its way to the hub." },
      { title: "Out for delivery", body: "Your order #{{1}} is out for delivery, arriving today by {{2}}. Track live: {{3}}" },
      { title: "Failed attempt", body: "We attempted delivery of order #{{1}} but couldn't reach you. Reschedule here: {{2}}" },
      { title: "COD reminder", body: "Reminder: keep ₹{{1}} ready for your COD order #{{2}}, arriving {{3}}." },
    ],
    integrations: [
      "Warehouse and fleet-management systems",
      "Courier and rider-allocation platforms",
      "Tally and other accounting software, for COD reconciliation",
      "Customer-facing tracking pages, via webhook",
    ],
    faq: [
      { q: "How does delivery OTP and masked calling work for riders?", a: "A delivery OTP is a short code sent to the customer by SMS that the rider collects at the door to confirm the handover, which cuts disputed deliveries. Masked calling connects the rider and customer through a proxy number so neither sees the other's real number; this runs as a Voice use case and needs to be registered as such rather than routed through an OTP-category line." },
      { q: "Why does each shipment stage need its own template?", a: "Pickup, out-for-delivery, failed attempt and COD reminder are distinct triggered events, and bundling them into one generic template is a common rejection reason at approval. Register an approved template per stage so each update maps to a real event and can be shown on request if a high-frequency sender is queried." },
      { q: "What is the best channel for a failed delivery and reschedule?", a: "Start with SMS carrying a reschedule link, and fall back to a Voice call when the SMS goes unread, since a missed delivery is time-sensitive. Keep the underlying delivery attempt logged and available on request, because high-frequency failed-attempt sends can otherwise get flagged." },
      { q: "Can we use voice broadcasts for COD confirmation at scale?", a: "Yes, and a Voice call confirms cash-in-hand before the rider is already at the door. At scale it needs its own registered use case; routing bulk COD voice calls through an OTP-category voice line gets them flagged. A simple automated call asking the customer to confirm works well for this." },
    ],
    relatedSolutions: ["/solutions/order-updates", "/solutions/payment-reminders", "/solutions/alerts"],
  },
  {
    slug: "/industries/travel",
    name: "Travel & Hospitality",
    group: "High volume",
    scenarios: [
      { moment: "Booking confirmation", detail: "A confirmation with the e-ticket or voucher attached." },
      { moment: "Check-in reminder", detail: "A notice when online check-in opens." },
      { moment: "Itinerary or schedule change", detail: "An urgent alert about a delay, gate change or cancellation." },
      { moment: "Post-stay feedback request", detail: "A one-tap rating request after checkout." },
    ],
    channelMix: [
      { moment: "Booking confirmation", channel: "WhatsApp", why: "Carries the e-ticket or voucher as a document in the message itself." },
      { moment: "Check-in reminder", channel: "SMS and WhatsApp", why: "Time-boxed and needs to land regardless of which app is opened." },
      { moment: "Schedule change", channel: "Voice and SMS", why: "Urgent enough to interrupt, regardless of channel preference." },
      { moment: "Feedback request", channel: "WhatsApp", why: "A quick-reply rating in a single tap." },
    ],
    complianceNotes: [
      "Time-critical alerts — a gate change, a delay, a cancellation — belong on a distinct urgent-transactional template category, so they aren't queued behind marketing traffic during peak travel periods.",
      "Post-stay feedback and offers are promotional and DND-scrubbed; sending them on the same transactional route as booking confirmations is a frequent, avoidable rejection.",
      "Guest communication in regional or international languages needs its own approved template per language — templates are not machine-translated by the platform.",
      "Bookings routed through a travel agency partner still need the end guest's own consent on file if MsgBridge messages them directly.",
    ],
    templatePack: [
      { title: "Booking confirmation", body: "Hi {{1}}, your booking {{2}} for {{3}} is confirmed. E-ticket: {{4}}" },
      { title: "Check-in reminder", body: "Reminder: check-in for {{1}} opens at {{2}}. Check in here: {{3}}" },
      { title: "Schedule change alert", body: "Update: your {{1}} on {{2}} has been changed to {{3}}. Details: {{4}}" },
      { title: "Feedback request", body: "Thanks for staying with us, {{1}}! Rate your experience: {{2}}" },
    ],
    integrations: [
      "Property management systems and GDS booking engines",
      "Travel agency and OTA platforms",
      "Payment and refund-processing systems",
      "CRM for guest history and loyalty programmes",
    ],
    faq: [
      { q: "How do we make sure a gate change or cancellation reaches the guest in time?", a: "Put time-critical alerts on a distinct urgent-transactional template category so they are not queued behind marketing traffic during peak travel periods. For genuine disruptions, combine Voice and SMS: the message is urgent enough to interrupt regardless of the guest's channel preference, and neither channel depends on an app being open." },
      { q: "Can we send the e-ticket or hotel voucher over WhatsApp?", a: "Yes. WhatsApp can carry the e-ticket or voucher as a document inside the booking-confirmation message itself, which is cleaner than a link. SMS remains a useful fallback for check-in reminders, which are time-boxed and need to land whichever app the guest happens to open." },
      { q: "Are post-stay feedback requests and offers treated differently from booking messages?", a: "Yes. Booking confirmations and schedule alerts are transactional, while post-stay feedback requests and offers are promotional and must be DND-scrubbed. Sending feedback or offers on the same transactional route as a confirmation is a frequent and avoidable rejection, so keep them on separate templates and routes." },
      { q: "How do we handle guests who booked through an OTA or travel agent?", a: "If MsgBridge messages the end guest directly, that guest's own consent must be on file, even when the booking came through an OTA or agency partner. For multi-language guest communication, register a separate approved template per language, since templates are not machine-translated by the platform." },
    ],
    relatedSolutions: ["/solutions/appointments", "/solutions/alerts", "/solutions/surveys"],
  },
  {
    slug: "/industries/education",
    name: "Education & EdTech",
    group: "Growth",
    scenarios: [
      { moment: "Fee due reminder", detail: "A reminder to parents ahead of a term's fee deadline." },
      { moment: "Class or exam schedule update", detail: "A same-day change notice sent to an entire batch." },
      { moment: "Attendance alert", detail: "A same-day notice to a parent when a student is marked absent." },
      { moment: "Admission enquiry follow-up", detail: "A response to a prospective family after they enquire." },
    ],
    channelMix: [
      { moment: "Fee due", channel: "SMS and WhatsApp", why: "WhatsApp for the fee link and receipt; SMS reaches every parent's phone." },
      { moment: "Schedule update", channel: "SMS", why: "Short, and reaches parents without needing a school app open." },
      { moment: "Attendance alert", channel: "SMS", why: "Needs to be fast and simple, sent the same day." },
      { moment: "Enquiry follow-up", channel: "WhatsApp chatbot", why: "Handles routine questions and hands off to a counsellor for serious enquiries." },
    ],
    complianceNotes: [
      "Messages to parents about an enrolled student are service communication, not marketing — but follow-ups to prospective families are promotional and need consent and DND-scrubbing.",
      "Fee reminders carrying a payment link must declare the URL pattern at template registration; a per-student dynamic link needs the dynamic-URL template category.",
      "Bulk schedule updates sent to a whole batch still map to an approved template per message type, since content changes from term to term.",
      "Regional-language communication to parents, common outside metro schools, changes SMS segment count and should be quoted for in advance.",
    ],
    templatePack: [
      { title: "Fee due", body: "Dear parent, the fee of ₹{{1}} for {{2}} is due on {{3}}. Pay online: {{4}}" },
      { title: "Schedule update", body: "{{1}}, please note: {{2}} on {{3}} has been rescheduled to {{4}}." },
      { title: "Attendance alert", body: "{{1}} was marked absent today, {{2}}. If this is unexpected, please contact the school office." },
      { title: "Enquiry follow-up", body: "Hi {{1}}, thanks for your interest in {{2}}. Reply to this message to speak with our admissions team." },
    ],
    integrations: [
      "Learning management systems (LMS)",
      "School and college ERP and fee-management software",
      "CRM for admissions pipelines",
      "Parent-communication apps, via webhook",
    ],
    faq: [
      { q: "Are messages to parents about an enrolled student treated as marketing?", a: "No. Communication to a parent about their enrolled child, such as an attendance alert or a fee reminder, is service communication and can run on a transactional route. Follow-ups to prospective families who only enquired are promotional, so they need consent and DND-scrubbing before the first message." },
      { q: "How do fee-payment links work in a DLT template?", a: "The URL pattern must be declared at template registration. A single fixed payment page can go in a standard template, but a link that changes per student needs the dynamic-URL template category. Fee reminders suit SMS and WhatsApp together: WhatsApp carries the link and receipt, SMS reaches every parent's phone." },
      { q: "Do we need a fresh template every time an exam schedule changes?", a: "You need an approved template per message type, not per individual send. A schedule-update template with variables for the class, date and new time covers repeated changes, so you are not re-registering each term; only a genuinely new message type needs a new template. Bulk batch updates still map to that approved template." },
      { q: "Does messaging parents in regional languages affect cost?", a: "Yes. Regional-language SMS is sent as Unicode, which shortens each segment and raises the segment count for the same text. This is common outside metro schools and worth quoting for in advance so a multi-language parent broadcast does not cost more than expected." },
    ],
    relatedSolutions: ["/solutions/payment-reminders", "/solutions/alerts", "/solutions/lead-generation"],
  },
  {
    slug: "/industries/real-estate",
    name: "Real Estate",
    group: "Growth",
    scenarios: [
      { moment: "Site-visit confirmation", detail: "A confirmation with the agent's contact and a location pin." },
      { moment: "Construction milestone update", detail: "A progress update to buyers on an under-construction project." },
      { moment: "Payment instalment reminder", detail: "A reminder ahead of a scheduled payment tied to a buyer agreement." },
      { moment: "Lead follow-up", detail: "A fast first response after a prospective buyer enquires." },
    ],
    channelMix: [
      { moment: "Site-visit confirmation", channel: "SMS and WhatsApp", why: "WhatsApp for the location pin and agent contact card." },
      { moment: "Milestone update", channel: "WhatsApp", why: "Carries photos or documents of construction progress." },
      { moment: "Instalment reminder", channel: "WhatsApp and SMS", why: "A large payment amount needs a clear, permanent written record." },
      { moment: "Lead follow-up", channel: "WhatsApp chatbot and Voice", why: "A fast first response matters in a long sales cycle." },
    ],
    complianceNotes: [
      "Lead-generation follow-ups are promotional by default and need consent captured at the point of enquiry — a website form or property portal — before the first WhatsApp message.",
      "Payment reminders tied to an active buyer agreement are service messages, but general project-launch marketing to the same buyer list is not — they need separate templates and routes.",
      "Project-wide construction updates sent to hundreds of buyers still require template approval per message variant, not a blanket approval covering \"updates.\"",
      "Possession-date and returns language is commonly flagged at template review — draft possession updates as indicative and tied to the buyer agreement, not as a standalone promise.",
    ],
    templatePack: [
      { title: "Site-visit confirmation", body: "Hi {{1}}, your site visit for {{2}} is confirmed on {{3}} at {{4}}. Agent: {{5}}" },
      { title: "Milestone update", body: "Construction update for {{1}}: {{2}} milestone completed. View photos: {{3}}" },
      { title: "Instalment reminder", body: "Reminder: instalment {{1}} of ₹{{2}} for {{3}} is due on {{4}}. Pay here: {{5}}" },
      { title: "Lead follow-up", body: "Hi {{1}}, thanks for your interest in {{2}}. Can we call you to share more details?" },
    ],
    integrations: [
      "CRM systems for lead and buyer management, such as Zoho and Salesforce",
      "Project ERP and construction-management software",
      "Payment gateways for instalment collection",
      "Property-portal lead feeds, via webhook",
    ],
    faq: [
      { q: "Can we message a lead the moment they enquire on a property portal?", a: "Only if consent was captured at the point of enquiry, such as the website form or portal listing. Lead-generation follow-ups are promotional by default, so that consent has to exist before the first WhatsApp message. With it in place, a WhatsApp chatbot or a Voice call gives the fast first response that matters in a long sales cycle." },
      { q: "Are instalment reminders treated the same as project marketing?", a: "No. A payment reminder tied to an active buyer agreement is a service message, while a project-launch or new-inventory push to the same buyer list is promotional. They need separate templates and routes, even when they go to the same person, because the promotional message must be DND-scrubbed and the service one need not be." },
      { q: "How should we word possession and returns messages?", a: "Carefully. Possession-date and returns language is commonly flagged at template review, so draft possession updates as indicative and tied to the buyer agreement rather than as a standalone promise or guarantee. Construction-milestone updates suit WhatsApp because it can carry progress photos or documents." },
      { q: "Do project-wide construction updates need approval for every variant?", a: "Yes. A construction update sent to hundreds of buyers still requires template approval per message variant; there is no blanket approval covering \"updates\" in general. Register each milestone or message type as its own template with variables for the project and stage." },
    ],
    relatedSolutions: ["/solutions/lead-generation", "/solutions/payment-reminders", "/solutions/appointments"],
  },
  {
    slug: "/industries/saas",
    name: "SaaS & Startups",
    group: "Growth",
    scenarios: [
      { moment: "Signup or login OTP", detail: "A verification code that has to land in seconds during onboarding." },
      { moment: "Trial-expiry reminder", detail: "A nudge before a free trial ends, with a direct upgrade link." },
      { moment: "Usage or billing alert", detail: "A short, factual notice about an invoice or a usage threshold." },
      { moment: "Re-engagement nudge", detail: "A message to a dormant user pointing at a new feature." },
    ],
    channelMix: [
      { moment: "Signup / login OTP", channel: "SMS, with Voice fallback", why: "Needs to land in seconds regardless of network conditions." },
      { moment: "Trial expiry", channel: "WhatsApp", why: "A direct upgrade link with a quick-reply performs better than email alone." },
      { moment: "Billing alert", channel: "SMS", why: "Short and factual, with no dependency on the app being installed." },
      { moment: "Re-engagement", channel: "WhatsApp", why: "Richer content for a nudge that has to earn attention." },
    ],
    complianceNotes: [
      "OTP and account-security messages must stay strictly transactional — routing them through a promotional-rate template to save cost is a common cause of failed delivery during signup spikes.",
      "Re-engagement and product-update nudges are promotional and DND-scrubbed by default, even for a B2B product, unless the recipient is a verified existing customer on a service route.",
      "DLT registration and TRAI rules apply only to Indian mobile numbers — international users fall outside their scope entirely.",
      "Template variants should be registered ahead of a launch, since approval queues don't move faster because a release date is close.",
    ],
    templatePack: [
      { title: "Signup / login OTP", body: "{{1}} is your verification code for {{2}}. Valid for {{3}} minutes." },
      { title: "Trial expiry", body: "Hi {{1}}, your trial for {{2}} ends on {{3}}. Upgrade now: {{4}}" },
      { title: "Billing alert", body: "Your invoice of ₹{{1}} for {{2}} is due on {{3}}. Pay here: {{4}}" },
      { title: "Re-engagement", body: "{{1}}, we've added {{2}} to {{3}}. Come see what's new: {{4}}" },
    ],
    integrations: [
      "Billing and subscription platforms such as Stripe, Razorpay and Chargebee",
      "Product-analytics tools, for trigger-based sends",
      "CRM and customer-success platforms",
      "In-app webhook events for real-time alerts",
    ],
    faq: [
      { q: "Which route should we use for signup and login OTPs?", a: "A strictly transactional route. Routing account-security OTPs through a cheaper promotional-rate template is a common cause of failed delivery during signup spikes, because promotional traffic is throttled and DND-scrubbed. Keep OTPs on a transactional template with a Voice fallback so the code lands in seconds regardless of network conditions." },
      { q: "Do DLT and TRAI rules apply to our international users?", a: "No. DLT registration and TRAI rules apply only to Indian mobile numbers. International users fall outside their scope entirely, so you route those messages through the relevant global channels instead. Only your India-facing SMS traffic needs DLT-registered templates and sender IDs." },
      { q: "Are re-engagement and product-update messages promotional even for a B2B product?", a: "Yes, by default. Re-engagement nudges and feature announcements are promotional and DND-scrubbed even for a B2B tool, unless the recipient is a verified existing customer being messaged on a service route about their own account. WhatsApp suits these nudges because it carries richer content that has to earn attention." },
      { q: "How far ahead of a launch should we register templates?", a: "Register template variants well before the release date. Approval queues do not move faster because a launch is close, so a same-week submission can miss the date. Draft and submit OTP, trial-expiry, billing and re-engagement templates ahead of time and treat approval as a lead-time dependency." },
    ],
    relatedSolutions: ["/solutions/otp-verification", "/solutions/alerts", "/solutions/lead-generation"],
  },
];

export const longTailSectors: { name: string; note: string; nearest: string }[] = [
  { name: "Automobile", note: "Service reminders, test-drive confirmations and delivery updates map closely to logistics and dealership patterns.", nearest: "/industries/logistics" },
  { name: "Jewellery", note: "High-value order confirmations, appointment bookings and festive campaigns follow the same shape as retail e-commerce.", nearest: "/industries/ecommerce" },
  { name: "Textiles", note: "Bulk order confirmations and dispatch updates for B2B buyers mirror logistics and e-commerce messaging.", nearest: "/industries/logistics" },
  { name: "Dairy", note: "Subscription delivery reminders and route updates run on the same order-and-delivery patterns as logistics.", nearest: "/industries/logistics" },
  { name: "Restaurants", note: "Table bookings, order confirmations and delivery updates follow travel and e-commerce messaging patterns.", nearest: "/industries/ecommerce" },
  { name: "Manufacturing", note: "Dispatch confirmations, payment reminders and dealer communication resemble B2B logistics and BFSI patterns.", nearest: "/industries/logistics" },
  { name: "Electronics", note: "Warranty registrations, service reminders and order updates follow the same shape as e-commerce and D2C.", nearest: "/industries/ecommerce" },
  { name: "Agriculture", note: "Advisory alerts, procurement confirmations and payment updates resemble government and BFSI messaging.", nearest: "/industries/government" },
  { name: "NGOs & Non-profits", note: "Donor acknowledgements, campaign updates and event reminders map to marketing and alert patterns.", nearest: "/industries/education" },
  { name: "Salons & Wellness", note: "Appointment bookings and reminders follow the same shape as healthcare and travel scheduling.", nearest: "/industries/healthcare" },
];
