import type { ServicePage } from "@/lib/types";

export const services: ServicePage[] = [
  {
    slug: "/services/dlt-registration",
    name: "DLT Registration Assistance",
    subLabel: "Entity ID, header, templates, TM chain binding",
    summary: "We handle the DLT registration paperwork end to end, so your team never has to learn the portal.",
    deliverables: [
      "Principal entity registration on the DLT platform",
      "Sender ID (header) registration, drafted to the 6-character rules",
      "Content template registration with variables declared correctly",
      "TM chain binding between entity, header and templates",
      "Consent and opt-in record-keeping set up for your account",
    ],
    whatYouProvide: [
      "Business registration documents (GST certificate, incorporation certificate)",
      "An authorised signatory for the entity registration form",
      "The message content you want to send, in draft form",
    ],
    process: [
      { stage: "Document collection and entity form preparation", timeline: "1-2 working days" },
      { stage: "Entity registration approval", timeline: "2-5 working days", outsideControl: true },
      { stage: "Header and template drafting", timeline: "1 working day" },
      { stage: "Header and template approval", timeline: "1-3 working days", outsideControl: true },
      { stage: "TM chain binding and final activation", timeline: "1 working day" },
    ],
    cost: { model: "included", detail: "Included with your MsgBridge plan for your first entity, header and up to 10 templates. Additional templates are billed per template." },
    rejectionPolicy: "If a header or template is rejected, we redraft and resubmit at no extra charge until it is approved. Rejections are almost always a wording or variable-placement issue we can see and fix before resubmitting.",
    faq: [
      { q: "How long does DLT registration actually take?", a: "Our part of the work is typically done within a day or two. The approval queues are run by the DLT operator and TRAI-registered entities, and their timelines are outside our control — we've listed realistic ranges above." },
      { q: "Do I need to do this myself if I switch from another provider?", a: "No. We can re-bind an existing DLT entity to MsgBridge's platform, or start a fresh registration if you prefer." },
      { q: "What happens if my business doesn't have a GST certificate?", a: "DLT registration requires a valid business registration document. We'll tell you exactly what's accepted for your entity type before you start." },
      { q: "Can I register more templates later?", a: "Yes, at any time. New templates go through the same drafting and approval process." },
    ],
  },
  {
    slug: "/services/whatsapp-verification",
    name: "WhatsApp Verification",
    subLabel: "Business verification and green tick",
    draft: true,
    summary: "We prepare and submit your WhatsApp Business verification, including the green tick application where you qualify.",
    deliverables: [
      "Business verification document preparation",
      "WhatsApp Business Manager setup and submission",
      "Green tick (official business account) application where eligible",
      "Guidance on the display name and profile that get approved fastest",
    ],
    whatYouProvide: [
      "Business registration documents matching your legal entity name",
      "A working business website and email on the same domain",
      "Access to your Meta Business Manager account",
    ],
    process: [
      { stage: "Business Manager setup and document preparation", timeline: "1-2 working days" },
      { stage: "Business verification review", timeline: "1-2 weeks", outsideControl: true },
      { stage: "Green tick application (if eligible)", timeline: "2-4 weeks", outsideControl: true },
    ],
    cost: { model: "one-off", detail: "A one-off setup fee, quoted based on whether a green tick application is included." },
    rejectionPolicy: "If verification is rejected, we review the reason, correct the documentation or profile details, and resubmit. Most rejections come from a mismatch between the legal name on file and the name shown on the account.",
    faq: [
      { q: "Is the green tick guaranteed?", a: "No. Eligibility and approval are decided by the platform, not by us. We apply on your behalf and tell you honestly if your business doesn't currently meet the criteria." },
      { q: "How long does business verification take?", a: "It sits in a platform review queue outside our control. The ranges above are realistic based on recent cases, not a guarantee." },
      { q: "What's the difference between verification and the green tick?", a: "Business verification confirms your account belongs to a real, registered business. The green tick is a separate, harder-to-get badge for a small number of well-known brands." },
      { q: "Can I use WhatsApp Business API without a green tick?", a: "Yes. Verification is required to send template messages at scale; the green tick is a badge, not a requirement to operate." },
    ],
  },
  {
    slug: "/services/chatbot-development",
    name: "Chatbot Design & Build",
    subLabel: "7-15 working days, subject to platform approval",
    summary: "We design, build and deploy a WhatsApp chatbot for your business, from conversation flow to live-agent handover.",
    deliverables: [
      "Conversation flow design for your top customer questions",
      "Automated replies, lead capture and order/service update flows",
      "CRM, ERP or website integration where needed",
      "Live-agent handover for anything the bot can't resolve",
      "Testing and a supervised launch",
    ],
    whatYouProvide: [
      "Your most common customer questions and current resolution flows",
      "Access to the systems the bot needs to connect to (CRM, ERP, booking system)",
      "Sign-off on the conversation flow before we build it",
    ],
    process: [
      { stage: "Requirements and conversation-flow design", timeline: "1-2 working days" },
      { stage: "WhatsApp API setup", timeline: "1 working day" },
      { stage: "Chatbot development and integration", timeline: "3-7 working days" },
      { stage: "Testing and your team's training", timeline: "1-2 working days" },
      { stage: "Launch, subject to WhatsApp's platform review", timeline: "1-3 working days", outsideControl: true },
    ],
    cost: { model: "quoted", detail: "Quoted per project based on the number of conversation flows and integrations. Ask for a quote with your requirements." },
    rejectionPolicy: "If WhatsApp's platform review flags your templates or bot messaging, we adjust the copy and resubmit at no extra charge. This is a normal part of launch, not a sign anything went wrong.",
    faq: [
      { q: "How complex can the chatbot be?", a: "From a simple FAQ-and-handover bot to a multi-step booking or lead-qualification flow. Complexity is the main driver of both cost and timeline." },
      { q: "Does the bot replace my support team?", a: "No. It handles repetitive questions and captures information, then hands off to a live agent for anything that needs a person." },
      { q: "Can the bot connect to my existing CRM?", a: "In most cases, yes, via API or webhook. Tell us what you use and we'll confirm during the requirements stage." },
      { q: "What happens after launch?", a: "We monitor the first few weeks of conversations with you and adjust flows that aren't performing." },
    ],
  },
  {
    slug: "/services/integration",
    name: "API Integration Support",
    summary: "Hands-on help wiring the MsgBridge API into your product, backend or existing systems.",
    deliverables: [
      "A technical walkthrough of the API with your engineering team",
      "Help mapping your send events (signup, order, payment) to the right endpoint",
      "Webhook setup for delivery reports and inbound replies",
      "Sandbox-to-production migration support",
    ],
    whatYouProvide: [
      "Access to a developer who can make the integration changes",
      "A description of where in your product each message should trigger",
    ],
    process: [
      { stage: "Technical scoping call", timeline: "1 working day" },
      { stage: "Sandbox integration and testing", timeline: "2-5 working days" },
      { stage: "Production credentials and go-live checklist", timeline: "1 working day" },
    ],
    cost: { model: "included", detail: "Included with every MsgBridge plan. There is no separate charge for integration support." },
    rejectionPolicy: "There's no approval queue here — if a test message fails, we debug the request together until it delivers, before you go live.",
    faq: [
      { q: "Do you provide SDKs?", a: "Yes, for the languages shown in the quickstart, with example requests for the rest via plain HTTP." },
      { q: "Can you help migrate from another provider?", a: "Yes. We'll map your existing send events to the equivalent MsgBridge endpoints." },
      { q: "Is there a staging environment?", a: "Yes, sandbox credentials let you test the full flow before switching to production keys." },
      { q: "What if our engineering team is small?", a: "That's exactly when this service helps most — we do the integration work with you, not just point you at documentation." },
    ],
  },
  {
    slug: "/services/social-leads",
    name: "Social Lead Generation",
    summary: "We run targeted social ads and creative, then move every inquiry into a WhatsApp follow-up so it doesn't go cold.",
    deliverables: [
      "Targeted ad campaigns by location, interest and age group",
      "Attention-grabbing, trust-building social creative and posts",
      "Automated WhatsApp follow-up for every inquiry",
      "Monitoring, reporting and ongoing optimisation",
    ],
    whatYouProvide: [
      "Your target customer profile and service area",
      "Product or service photos and pricing for creative",
      "A WhatsApp Business number for follow-up conversations",
    ],
    process: [
      { stage: "Discuss goals and target audience", timeline: "1 working day" },
      { stage: "Plan campaign creative and targeting", timeline: "2-3 working days" },
      { stage: "Launch ads and WhatsApp follow-up flow", timeline: "1 working day" },
      { stage: "Ongoing monitoring and optimisation", timeline: "Continuous, reviewed weekly" },
    ],
    cost: { model: "quoted", detail: "Quoted as a monthly management fee plus your ad spend, based on target volume and region." },
    rejectionPolicy: "If a platform rejects an ad for policy reasons, we revise the creative and resubmit at no extra charge — this is common with regulated categories like finance and healthcare.",
    faq: [
      { q: "Which platforms do you run ads on?", a: "Meta platforms (Facebook and Instagram) are the primary channels, chosen for the WhatsApp follow-up integration." },
      { q: "How fast do leads start coming in?", a: "Once ads are live, inquiries typically start within the first few days, though volume builds as targeting is refined." },
      { q: "Do you close the sale for us?", a: "No. We generate and qualify the inquiry and start the WhatsApp conversation; your team closes the sale." },
      { q: "Is this only for large businesses?", a: "No. It's built for local services, consultants and SMEs who don't have an in-house ads team." },
    ],
  },
];
