import type { SolutionPage } from "@/lib/types";

export const solutions: SolutionPage[] = [
  {
    slug: "/solutions/otp-verification",
    name: "OTP & User Verification",
    problem: "Customers miss the OTP and abandon signup. One slow SMS costs you a new user before they ever see your product.",
    channels: [
      { name: "SMS", why: "Fastest first attempt, works on every handset, no app install needed." },
      { name: "WhatsApp", why: "A second attempt when SMS delivery is uncertain, with read receipts." },
      { name: "Voice call", why: "The channel of last resort when text delivery fails outright.", recommended: false },
      { name: "MsgBridge Verify", why: "Runs SMS, then WhatsApp, then a voice call in one API call, until the code lands.", recommended: true },
    ],
    flow: {
      trigger: "User taps \"send code\" on signup or login",
      primary: "OTP sent by SMS",
      fallback: "WhatsApp after 12 seconds, then a voice call after 15 more",
      outcome: "User enters the code and is verified, on whichever channel it reached them",
    },
    templates: [
      { title: "Login OTP", body: "{{otp}} is your MsgBridge login code. Valid for 10 minutes. Do not share this code with anyone." },
      { title: "Signup verification", body: "Welcome to {{brand}}. Your verification code is {{otp}}. It expires in 10 minutes." },
      { title: "Password reset", body: "Use {{otp}} to reset your {{brand}} password. If you did not request this, ignore this message." },
    ],
    setup: [
      { step: "Register the OTP header and content template on DLT", owner: "MsgBridge" },
      { step: "Share your signup and login flow so the API call sits in the right place", owner: "You" },
      { step: "Integrate the Verify API and configure channel order and timeouts", owner: "You" },
      { step: "Test the full cascade end to end before going live", owner: "MsgBridge" },
    ],
    relatedIndustries: ["/industries/bfsi", "/industries/ecommerce", "/industries/saas"],
    relatedProducts: ["/verify", "/sms/otp", "/voice/otp"],
  },
  {
    slug: "/solutions/alerts",
    name: "Alerts & Notifications",
    problem: "Customers find out about a failed payment, a security login, or a service outage too late, then call support angry instead of informed.",
    channels: [
      { name: "SMS", why: "Reaches every phone instantly, no data connection required.", recommended: true },
      { name: "WhatsApp", why: "Richer formatting and a delivery tick the customer can see." },
      { name: "Voice call", why: "For alerts serious enough to need a human to pick up the phone." },
    ],
    flow: {
      trigger: "A system event fires: failed payment, low balance, security login, service disruption",
      primary: "SMS alert sent within seconds of the event",
      fallback: "WhatsApp copy sent in parallel for a richer, trackable version",
      outcome: "Customer acts on the alert before it becomes a support ticket",
    },
    templates: [
      { title: "Payment failure", body: "Your payment of {{amount}} for {{service}} failed. Retry at {{link}} to avoid interruption." },
      { title: "Security login alert", body: "New login to your {{brand}} account from {{device}} at {{time}}. Not you? Reply STOP to secure your account." },
      { title: "Low balance", body: "Your {{brand}} wallet balance is {{amount}}. Recharge now to keep your service active." },
    ],
    setup: [
      { step: "Register alert templates on DLT under the transactional category", owner: "MsgBridge" },
      { step: "Identify the system events that should trigger an alert", owner: "You" },
      { step: "Wire the trigger to the SMS/WhatsApp send API via webhook or backend call", owner: "You" },
      { step: "Set up delivery-report monitoring so failed alerts are visible", owner: "MsgBridge" },
    ],
    relatedIndustries: ["/industries/bfsi", "/industries/insurance", "/industries/logistics"],
    relatedProducts: ["/sms/transactional", "/whatsapp-business-api", "/voice/tts"],
  },
  {
    slug: "/solutions/marketing",
    name: "Marketing Campaigns",
    problem: "Promotional blasts get ignored, filtered by DND, or sent outside TRAI's permitted hours and never reach anyone at all.",
    channels: [
      { name: "SMS", why: "Cheapest reach at volume, works for every regional-language audience." },
      { name: "WhatsApp", why: "Media-rich campaigns with buttons, read receipts and a reply channel.", recommended: true },
      { name: "RCS", why: "Branded, verified rich cards for audiences on RCS-capable handsets." },
    ],
    flow: {
      trigger: "A campaign is scheduled: a sale, a new product, a seasonal offer",
      primary: "WhatsApp campaign to opted-in customers with images and a reply button",
      fallback: "SMS to the segment without WhatsApp opt-in, DND-scrubbed",
      outcome: "Customer clicks through or replies, tracked back to the campaign",
    },
    templates: [
      { title: "Sale announcement", body: "{{brand}}: {{discount}} off everything, this weekend only. Shop now: {{link}}. Reply STOP to opt out." },
      { title: "New product launch", body: "Introducing {{product}} from {{brand}}. See it first: {{link}}." },
    ],
    setup: [
      { step: "Register promotional headers, templates and DND-scrub the send list", owner: "MsgBridge" },
      { step: "Provide the customer list with valid opt-in consent records", owner: "You" },
      { step: "Approve creative and copy for each campaign", owner: "You" },
      { step: "Schedule and send within TRAI's permitted time windows", owner: "MsgBridge" },
    ],
    relatedIndustries: ["/industries/ecommerce", "/industries/travel", "/industries/real-estate"],
    relatedProducts: ["/sms/promotional", "/whatsapp-business-api", "/rcs"],
  },
  {
    slug: "/solutions/support",
    name: "Customer Support",
    problem: "Support requests arrive across email, a phone line and social media with no single view, so customers repeat themselves to every new agent.",
    channels: [
      { name: "WhatsApp", why: "One thread per customer, with a shared team inbox and chat history.", recommended: true },
      { name: "AI Chatbot", why: "Answers common questions instantly and hands off to a live agent only when needed." },
      { name: "SMS", why: "A fallback channel for customers without WhatsApp." },
    ],
    flow: {
      trigger: "Customer messages the business WhatsApp number with a question",
      primary: "Chatbot answers common queries or captures the request",
      fallback: "Live-agent handover for anything the bot cannot resolve",
      outcome: "Customer gets an answer in one thread, without repeating themselves",
    },
    templates: [
      { title: "Support session opener", body: "Hi {{name}}, thanks for reaching {{brand}} support. How can we help today?" },
      { title: "Ticket update", body: "Your support ticket {{ticket_id}} has been updated. View the response: {{link}}." },
    ],
    setup: [
      { step: "Set up the WhatsApp team inbox and agent routing rules", owner: "MsgBridge" },
      { step: "Provide your FAQ content and common resolution flows", owner: "You" },
      { step: "Build and test the chatbot's automated replies", owner: "MsgBridge" },
      { step: "Train your support team on the shared inbox", owner: "You" },
    ],
    relatedIndustries: ["/industries/ecommerce", "/industries/travel", "/industries/saas"],
    relatedProducts: ["/whatsapp-business-api", "/whatsapp-chatbot", "/sms/transactional"],
  },
  {
    slug: "/solutions/commerce",
    name: "Conversational Commerce",
    problem: "Customers browse on Instagram or Google, then hit a checkout form that feels like a chore and abandon the cart.",
    channels: [
      { name: "WhatsApp", why: "Catalogues, in-chat payments and buttons let customers buy inside the conversation.", recommended: true },
      { name: "RCS", why: "Rich carousels for product discovery on supported handsets." },
    ],
    flow: {
      trigger: "Customer messages or clicks through from an ad",
      primary: "WhatsApp catalogue and guided buying flow",
      fallback: "SMS link to the same product if WhatsApp is not available",
      outcome: "Customer completes the purchase inside the chat thread",
    },
    templates: [
      { title: "Cart reminder", body: "You left {{item}} in your cart, {{name}}. Complete your order: {{link}}." },
      { title: "Order confirmation", body: "Thanks for your order, {{name}}! {{order_id}} is confirmed. We'll message you when it ships." },
    ],
    setup: [
      { step: "Set up the WhatsApp catalogue and payment integration", owner: "MsgBridge" },
      { step: "Provide your product catalogue and pricing", owner: "You" },
      { step: "Connect the buying flow to your order management system", owner: "You" },
      { step: "Test the end-to-end purchase flow before launch", owner: "MsgBridge" },
    ],
    relatedIndustries: ["/industries/ecommerce", "/industries/real-estate"],
    relatedProducts: ["/whatsapp-business-api", "/rcs", "/whatsapp-chatbot"],
  },
  {
    slug: "/solutions/payment-reminders",
    name: "Payment & Collection Reminders",
    problem: "Customers forget an EMI or bill due date, and a call centre chasing every late payment costs more than the payment itself.",
    channels: [
      { name: "SMS", why: "A short, unmissable nudge a few days before the due date.", recommended: true },
      { name: "Voice (Press-1)", why: "An automated call for overdue accounts, with press-1 to confirm or connect to an agent." },
      { name: "WhatsApp", why: "A payment link and receipt in one trackable thread." },
    ],
    flow: {
      trigger: "A due date approaches or passes on a loan, EMI or bill",
      primary: "SMS reminder 3 days before the due date",
      fallback: "Press-1 voice call if the bill is still unpaid after the due date",
      outcome: "Customer pays on time or is connected to an agent for overdue accounts",
    },
    templates: [
      { title: "Upcoming due date", body: "Hi {{name}}, your {{bill_type}} of {{amount}} is due on {{date}}. Pay now: {{link}}." },
      { title: "Overdue notice", body: "Your {{bill_type}} payment of {{amount}} is overdue. Pay now to avoid late charges: {{link}}." },
    ],
    setup: [
      { step: "Register payment-reminder templates and the press-1 voice script", owner: "MsgBridge" },
      { step: "Provide the billing schedule and due-date data feed", owner: "You" },
      { step: "Set the reminder cadence: days before and after due date", owner: "You" },
      { step: "Route press-1 confirmations to your collections team", owner: "MsgBridge" },
    ],
    relatedIndustries: ["/industries/bfsi", "/industries/insurance"],
    relatedProducts: ["/sms/transactional", "/voice/press-1", "/whatsapp-business-api"],
  },
  {
    slug: "/solutions/order-updates",
    name: "Order & Delivery Updates",
    problem: "Customers call to ask \"where is my order\" because the only update they got was a single email that landed in spam.",
    channels: [
      { name: "WhatsApp", why: "Order confirmed, shipped, out for delivery and delivered, all in one thread.", recommended: true },
      { name: "SMS", why: "A reliable fallback for customers without WhatsApp opted in." },
    ],
    flow: {
      trigger: "An order status changes in your logistics or order-management system",
      primary: "WhatsApp update at each status change",
      fallback: "SMS if the WhatsApp message is undelivered within 30 seconds",
      outcome: "Customer always knows where the order is, without contacting support",
    },
    templates: [
      { title: "Order shipped", body: "Your order {{order_id}} has shipped and is on its way. Track it: {{link}}." },
      { title: "Out for delivery", body: "Your order {{order_id}} is out for delivery today. {{courier_name}} will call before arrival." },
      { title: "Failed delivery attempt", body: "We tried to deliver {{order_id}} but missed you. Reschedule here: {{link}}." },
    ],
    setup: [
      { step: "Register order-lifecycle templates covering every status", owner: "MsgBridge" },
      { step: "Connect your order-management or logistics webhook to the send API", owner: "You" },
      { step: "Map each status change to the right template", owner: "You" },
      { step: "Monitor delivery reports for undelivered updates", owner: "MsgBridge" },
    ],
    relatedIndustries: ["/industries/ecommerce", "/industries/logistics"],
    relatedProducts: ["/whatsapp-business-api", "/sms/transactional", "/rcs"],
  },
  {
    slug: "/solutions/appointments",
    name: "Appointment Reminders",
    problem: "Patients and clients forget appointments, and every no-show is an empty slot that could have gone to someone else.",
    channels: [
      { name: "SMS", why: "A simple reminder that reaches every patient, regardless of smartphone or app.", recommended: true },
      { name: "WhatsApp", why: "A reminder with a one-tap reschedule or confirm button." },
      { name: "Voice (Press-1)", why: "A call for high-value appointments where confirmation matters." },
    ],
    flow: {
      trigger: "An appointment is booked in your scheduling system",
      primary: "SMS reminder 24 hours before the appointment",
      fallback: "A second reminder 2 hours before, on WhatsApp if opted in",
      outcome: "Patient or client confirms, reschedules, or shows up on time",
    },
    templates: [
      { title: "Appointment reminder", body: "Reminder: your appointment with {{provider}} is on {{date}} at {{time}}. Reply C to confirm or R to reschedule." },
      { title: "Same-day reminder", body: "Your appointment is today at {{time}} with {{provider}} at {{location}}." },
    ],
    setup: [
      { step: "Register reminder templates for each appointment type", owner: "MsgBridge" },
      { step: "Connect your scheduling or practice-management system", owner: "You" },
      { step: "Set the reminder timing: 24 hours, 2 hours, or both", owner: "You" },
      { step: "Route confirm/reschedule replies back to your booking system", owner: "MsgBridge" },
    ],
    relatedIndustries: ["/industries/healthcare", "/industries/education", "/industries/real-estate"],
    relatedProducts: ["/sms/transactional", "/whatsapp-business-api", "/voice/press-1"],
  },
  {
    slug: "/solutions/lead-generation",
    name: "Lead Capture & Qualification",
    problem: "Leads come in from ads and forms, then sit unanswered for hours while a competitor's faster follow-up wins the sale.",
    channels: [
      { name: "WhatsApp", why: "An instant reply the moment a lead submits a form, then a human takes over.", recommended: true },
      { name: "SMS", why: "A fast acknowledgement even before the WhatsApp conversation starts." },
      { name: "AI Chatbot", why: "Qualifies the lead with a few questions before it reaches a salesperson." },
    ],
    flow: {
      trigger: "A lead submits a form or messages from an ad",
      primary: "WhatsApp auto-reply with qualifying questions within seconds",
      fallback: "SMS acknowledgement if the lead has not opted into WhatsApp",
      outcome: "A qualified lead lands in your CRM with context, ready for follow-up",
    },
    templates: [
      { title: "Instant lead reply", body: "Hi {{name}}, thanks for your interest in {{product}}. Quick question: {{qualifying_question}}?" },
      { title: "Follow-up nudge", body: "Hi {{name}}, still interested in {{product}}? Reply YES and we'll call you today." },
    ],
    setup: [
      { step: "Register the lead-capture template and set up the chatbot flow", owner: "MsgBridge" },
      { step: "Provide qualifying questions and your CRM's lead endpoint", owner: "You" },
      { step: "Connect the ad or form source to trigger the auto-reply", owner: "You" },
      { step: "Test the handoff from bot to sales team", owner: "MsgBridge" },
    ],
    relatedIndustries: ["/industries/real-estate", "/industries/education", "/industries/saas"],
    relatedProducts: ["/whatsapp-chatbot", "/whatsapp-business-api", "/sms/transactional"],
  },
  {
    slug: "/solutions/surveys",
    name: "Surveys & Feedback",
    problem: "Feedback forms sent by email get a single-digit response rate, so you make decisions without hearing from most customers.",
    channels: [
      { name: "WhatsApp", why: "A quick-reply survey inside a channel customers already check.", recommended: true },
      { name: "SMS", why: "A one-question rating survey that takes five seconds to answer." },
      { name: "Voice (Press-1)", why: "A short automated call for a single satisfaction rating." },
    ],
    flow: {
      trigger: "A purchase, support ticket, or appointment is completed",
      primary: "WhatsApp survey with quick-reply buttons sent within an hour",
      fallback: "SMS one-question rating if WhatsApp is not available",
      outcome: "Feedback lands in your dashboard, tagged to the specific interaction",
    },
    templates: [
      { title: "Post-purchase survey", body: "How was your experience with {{brand}}, {{name}}? Reply 1-5." },
      { title: "Support satisfaction check", body: "Did {{agent_name}} resolve your issue today? Reply YES or NO." },
    ],
    setup: [
      { step: "Register the survey template and set up quick-reply buttons", owner: "MsgBridge" },
      { step: "Decide which interactions trigger a survey", owner: "You" },
      { step: "Connect responses to your feedback dashboard", owner: "MsgBridge" },
      { step: "Review response trends and adjust the question set", owner: "You" },
    ],
    relatedIndustries: ["/industries/ecommerce", "/industries/healthcare", "/industries/travel"],
    relatedProducts: ["/whatsapp-business-api", "/sms/transactional", "/voice/press-1"],
  },
];
