import type { SolutionPage } from "@/lib/types";

export const solutions: SolutionPage[] = [
  {
    slug: "/solutions/otp-verification",
    name: "OTP & User Verification",
    problem: "Customers miss the OTP and abandon signup. One slow SMS costs you a new user before they ever see your product.",
    channels: [
      { name: "SMS", why: "Fastest first attempt, works on every handset, no app install needed." },
      { name: "WhatsApp", why: "A second attempt when SMS delivery is uncertain, with read receipts." },
      { name: "Voice call", why: "The channel of last resort when text delivery fails outright.", recommended: false },
      { name: "MsgBridge Verify", why: "Runs SMS, then WhatsApp, then a voice call in one API call, until the code lands.", recommended: true },
    ],
    flow: {
      trigger: "User taps \"send code\" on signup or login",
      primary: "OTP sent by SMS",
      fallback: "WhatsApp after 12 seconds, then a voice call after 15 more",
      outcome: "User enters the code and is verified, on whichever channel it reached them",
    },
    templates: [
      { title: "Login OTP", body: "{{otp}} is your MsgBridge login code. Valid for 10 minutes. Do not share this code with anyone." },
      { title: "Signup verification", body: "Welcome to {{brand}}. Your verification code is {{otp}}. It expires in 10 minutes." },
      { title: "Password reset", body: "Use {{otp}} to reset your {{brand}} password. If you did not request this, ignore this message." },
    ],
    setup: [
      { step: "Register the OTP header and content template on DLT", owner: "MsgBridge" },
      { step: "Share your signup and login flow so the API call sits in the right place", owner: "You" },
      { step: "Integrate the Verify API and configure channel order and timeouts", owner: "You" },
      { step: "Test the full cascade end to end before going live", owner: "MsgBridge" },
    ],
    integration: "Call the Verify API from your signup or login backend the moment a user requests a code. MsgBridge runs the SMS-WhatsApp-voice cascade and returns a single verification result you check against the user's input; delivery and channel-used reports post back to your webhook so you can see which channel closed each verification.",
    metrics: ["Delivery rate per channel", "Verification completion rate", "Median time to verify", "Fallback rate from SMS to WhatsApp or voice", "First-attempt success rate"],
    faq: [
      { q: "What happens if the first SMS never arrives?", a: "The cascade escalates on its own. If the SMS is not confirmed within your configured window, MsgBridge retries on WhatsApp, then places a voice call reading the code aloud, all inside one API call, so the user is not left waiting." },
      { q: "Can I verify users on WhatsApp instead of SMS?", a: "Yes. You can set WhatsApp as the first channel, or run it as the fallback. WhatsApp verification needs an approved template and the number to have opted in; SMS remains the most universal first attempt because it needs no app or data connection." },
      { q: "Do I need DLT registration for OTP SMS?", a: "Yes. OTP messages in India are sent under DLT-registered transactional headers and templates. We register the header and content template for you as part of setup before you go live." },
      { q: "How long should an OTP stay valid?", a: "A 5 to 10 minute expiry is typical and is set in your own verification logic. MsgBridge delivers the code; you control how long it is accepted and how many attempts are allowed." },
    ],
    relatedIndustries: ["/industries/bfsi", "/industries/ecommerce", "/industries/saas"],
    relatedProducts: ["/verify", "/sms/otp", "/voice/otp"],
  },
  {
    slug: "/solutions/alerts",
    name: "Alerts & Notifications",
    problem: "Customers find out about a failed payment, a security login, or a service outage too late, then call support angry instead of informed.",
    channels: [
      { name: "SMS", why: "Reaches every phone instantly, no data connection required.", recommended: true },
      { name: "WhatsApp", why: "Richer formatting and a delivery tick the customer can see." },
      { name: "Voice call", why: "For alerts serious enough to need a human to pick up the phone." },
    ],
    flow: {
      trigger: "A system event fires: failed payment, low balance, security login, service disruption",
      primary: "SMS alert sent within seconds of the event",
      fallback: "WhatsApp copy sent in parallel for a richer, trackable version",
      outcome: "Customer acts on the alert before it becomes a support ticket",
    },
    templates: [
      { title: "Payment failure", body: "Your payment of {{amount}} for {{service}} failed. Retry at {{link}} to avoid interruption." },
      { title: "Security login alert", body: "New login to your {{brand}} account from {{device}} at {{time}}. Not you? Reply STOP to secure your account." },
      { title: "Low balance", body: "Your {{brand}} wallet balance is {{amount}}. Recharge now to keep your service active." },
    ],
    setup: [
      { step: "Register alert templates on DLT under the transactional category", owner: "MsgBridge" },
      { step: "Identify the system events that should trigger an alert", owner: "You" },
      { step: "Wire the trigger to the SMS/WhatsApp send API via webhook or backend call", owner: "You" },
      { step: "Set up delivery-report monitoring so failed alerts are visible", owner: "MsgBridge" },
    ],
    integration: "Fire the alert from wherever the event happens, your payment gateway, auth service, or monitoring system, by calling the send API or posting to a webhook. Pick the channel per event type, send SMS and WhatsApp in parallel where speed matters, and receive delivery reports back so an undelivered critical alert surfaces instead of failing silently.",
    metrics: ["Time from event to alert sent", "Delivery rate", "Read rate on WhatsApp", "Support tickets deflected", "Undelivered-alert rate flagged for retry"],
    faq: [
      { q: "How fast does an alert go out after the event?", a: "Sending is triggered the instant your system calls the API, so the message leaves within seconds of the event. Actual handset delivery depends on the operator, which is why critical alerts can go out on SMS and WhatsApp together." },
      { q: "Can transactional alerts go to DND numbers?", a: "Genuine transactional and service alerts, such as a failed payment or a security login, are delivered on transactional headers and are not blocked by DND. They must be registered under the correct DLT category and stay free of promotional content." },
      { q: "Should I send the same alert on both SMS and WhatsApp?", a: "For high-stakes alerts, yes, send in parallel: SMS guarantees reach on any handset while WhatsApp adds a read receipt and richer formatting. For routine notices, a single channel keeps costs down." },
      { q: "Can customers reply to an alert?", a: "On WhatsApp they can reply and reach your team or bot. SMS alerts are usually one-way, though you can include a link or a keyword like STOP for the customer to act on." },
    ],
    relatedIndustries: ["/industries/bfsi", "/industries/insurance", "/industries/logistics"],
    relatedProducts: ["/sms/transactional", "/whatsapp-business-api", "/voice/tts"],
  },
  {
    slug: "/solutions/marketing",
    name: "Marketing Campaigns",
    problem: "Promotional blasts get ignored, filtered by DND, or sent outside TRAI's permitted hours and never reach anyone at all.",
    channels: [
      { name: "SMS", why: "Cheapest reach at volume, works for every regional-language audience." },
      { name: "WhatsApp", why: "Media-rich campaigns with buttons, read receipts and a reply channel.", recommended: true },
      { name: "RCS", why: "Branded, verified rich cards for audiences on RCS-capable handsets." },
    ],
    flow: {
      trigger: "A campaign is scheduled: a sale, a new product, a seasonal offer",
      primary: "WhatsApp campaign to opted-in customers with images and a reply button",
      fallback: "SMS to the segment without WhatsApp opt-in, DND-scrubbed",
      outcome: "Customer clicks through or replies, tracked back to the campaign",
    },
    templates: [
      { title: "Sale announcement", body: "{{brand}}: {{discount}} off everything, this weekend only. Shop now: {{link}}. Reply STOP to opt out." },
      { title: "New product launch", body: "Introducing {{product}} from {{brand}}. See it first: {{link}}." },
    ],
    setup: [
      { step: "Register promotional headers, templates and DND-scrub the send list", owner: "MsgBridge" },
      { step: "Provide the customer list with valid opt-in consent records", owner: "You" },
      { step: "Approve creative and copy for each campaign", owner: "You" },
      { step: "Schedule and send within TRAI's permitted time windows", owner: "MsgBridge" },
    ],
    integration: "Sync segments from your CRM or e-commerce platform, then trigger a campaign through the API or the dashboard. MsgBridge DND-scrubs the list, sends on the chosen channel within permitted hours, and posts delivery, click and opt-out events back so you can attribute results and update consent records in your own system.",
    metrics: ["Delivery rate", "Click-through rate on links", "Reply rate on WhatsApp", "Opt-out rate", "Conversions attributed to the campaign"],
    faq: [
      { q: "Do I need consent to send marketing messages?", a: "Yes. Promotional SMS goes to opted-in numbers after a DND scrub, and WhatsApp marketing requires the customer to have opted in and an approved template. We help you keep consent records aligned with what you send." },
      { q: "When can promotional SMS be sent?", a: "Promotional messages are restricted to the time windows permitted by TRAI regulations and are not delivered outside them. Campaigns are scheduled to land inside those windows automatically." },
      { q: "Which channel converts better, SMS or WhatsApp?", a: "It depends on your audience. WhatsApp supports images, buttons and replies, so it usually drives richer engagement from opted-in customers, while SMS gives the widest low-cost reach. Many teams use WhatsApp for opted-in segments and SMS for the rest." },
      { q: "How is a marketing template approved?", a: "WhatsApp marketing templates are submitted for approval before use, and promotional SMS content is registered on DLT. Both are handled during campaign setup so your creative is cleared before send." },
    ],
    relatedIndustries: ["/industries/ecommerce", "/industries/travel", "/industries/real-estate"],
    relatedProducts: ["/sms/promotional", "/whatsapp-business-api", "/rcs"],
  },
  {
    slug: "/solutions/support",
    name: "Customer Support",
    problem: "Support requests arrive across email, a phone line and social media with no single view, so customers repeat themselves to every new agent.",
    channels: [
      { name: "WhatsApp", why: "One thread per customer, with a shared team inbox and chat history.", recommended: true },
      { name: "AI Chatbot", why: "Answers common questions instantly and hands off to a live agent only when needed." },
      { name: "SMS", why: "A fallback channel for customers without WhatsApp." },
    ],
    flow: {
      trigger: "Customer messages the business WhatsApp number with a question",
      primary: "Chatbot answers common queries or captures the request",
      fallback: "Live-agent handover for anything the bot cannot resolve",
      outcome: "Customer gets an answer in one thread, without repeating themselves",
    },
    templates: [
      { title: "Support session opener", body: "Hi {{name}}, thanks for reaching {{brand}} support. How can we help today?" },
      { title: "Ticket update", body: "Your support ticket {{ticket_id}} has been updated. View the response: {{link}}." },
    ],
    setup: [
      { step: "Set up the WhatsApp team inbox and agent routing rules", owner: "MsgBridge" },
      { step: "Provide your FAQ content and common resolution flows", owner: "You" },
      { step: "Build and test the chatbot's automated replies", owner: "MsgBridge" },
      { step: "Train your support team on the shared inbox", owner: "You" },
    ],
    integration: "Route your WhatsApp business number into the shared team inbox, where the chatbot handles first contact and hands off to agents. Connect it to your CRM or helpdesk so tickets, customer history and order data appear alongside the thread, and conversation events sync back to keep both systems current.",
    metrics: ["First response time", "Bot resolution rate before handover", "Average handling time per agent", "Reopen rate", "Customer satisfaction score"],
    faq: [
      { q: "Can the chatbot hand a conversation to a human?", a: "Yes. The bot answers common questions and, whenever it cannot resolve something or the customer asks, it hands the full thread to a live agent in the shared inbox, so nothing is repeated." },
      { q: "Can several agents share one WhatsApp number?", a: "Yes. The team inbox lets multiple agents work from a single business number with routing and assignment rules, so each customer keeps one continuous thread regardless of who replies." },
      { q: "Does it connect to my existing helpdesk or CRM?", a: "Conversations and customer context can be linked to your CRM or helpdesk through the API so agents see history in one place. Tell us which tools you run and we scope the integration during setup." },
      { q: "What about customers who do not use WhatsApp?", a: "SMS acts as a fallback so those customers still reach support and receive ticket updates, while WhatsApp remains the primary threaded channel for everyone else." },
    ],
    relatedIndustries: ["/industries/ecommerce", "/industries/travel", "/industries/saas"],
    relatedProducts: ["/whatsapp-business-api", "/whatsapp-chatbot", "/sms/transactional"],
  },
  {
    slug: "/solutions/commerce",
    name: "Conversational Commerce",
    problem: "Customers browse on Instagram or Google, then hit a checkout form that feels like a chore and abandon the cart.",
    channels: [
      { name: "WhatsApp", why: "Catalogues, in-chat payments and buttons let customers buy inside the conversation.", recommended: true },
      { name: "RCS", why: "Rich carousels for product discovery on supported handsets." },
    ],
    flow: {
      trigger: "Customer messages or clicks through from an ad",
      primary: "WhatsApp catalogue and guided buying flow",
      fallback: "SMS link to the same product if WhatsApp is not available",
      outcome: "Customer completes the purchase inside the chat thread",
    },
    templates: [
      { title: "Cart reminder", body: "You left {{item}} in your cart, {{name}}. Complete your order: {{link}}." },
      { title: "Order confirmation", body: "Thanks for your order, {{name}}! {{order_id}} is confirmed. We'll message you when it ships." },
    ],
    setup: [
      { step: "Set up the WhatsApp catalogue and payment integration", owner: "MsgBridge" },
      { step: "Provide your product catalogue and pricing", owner: "You" },
      { step: "Connect the buying flow to your order management system", owner: "You" },
      { step: "Test the end-to-end purchase flow before launch", owner: "MsgBridge" },
    ],
    integration: "Connect your product catalogue and order-management system to WhatsApp so customers browse, pick and confirm inside the chat. Ads and links drop customers straight into the thread; orders created in-chat flow to your OMS, and payment and order-status events sync back so fulfilment runs on your existing stack.",
    metrics: ["Chat-to-order conversion rate", "Cart abandonment recovered", "Average order value in chat", "In-chat payment completion rate", "Repeat purchase rate"],
    faq: [
      { q: "Can customers pay inside the WhatsApp chat?", a: "Yes. With WhatsApp payment options and payment links, a customer can complete checkout without leaving the conversation, which removes the drop-off of a separate checkout form." },
      { q: "How do product catalogues work on WhatsApp?", a: "Your catalogue is set up so customers can browse items, ask questions and add to an order in the thread. Keeping product and price data in sync with your store is part of the integration." },
      { q: "Does an in-chat order reach my order system?", a: "Yes. The buying flow connects to your order-management system so a chat purchase creates a real order and confirmations, and shipping updates can follow in the same thread." },
      { q: "Do customers need to opt in first?", a: "To message a customer proactively, yes, WhatsApp requires opt-in and approved templates. When the customer starts the conversation, such as clicking through from an ad, you can reply freely within the session window." },
    ],
    relatedIndustries: ["/industries/ecommerce", "/industries/real-estate"],
    relatedProducts: ["/whatsapp-business-api", "/rcs", "/whatsapp-chatbot"],
  },
  {
    slug: "/solutions/payment-reminders",
    name: "Payment & Collection Reminders",
    problem: "Customers forget an EMI or bill due date, and a call centre chasing every late payment costs more than the payment itself.",
    channels: [
      { name: "SMS", why: "A short, unmissable nudge a few days before the due date.", recommended: true },
      { name: "Voice (Press-1)", why: "An automated call for overdue accounts, with press-1 to confirm or connect to an agent." },
      { name: "WhatsApp", why: "A payment link and receipt in one trackable thread." },
    ],
    flow: {
      trigger: "A due date approaches or passes on a loan, EMI or bill",
      primary: "SMS reminder 3 days before the due date",
      fallback: "Press-1 voice call if the bill is still unpaid after the due date",
      outcome: "Customer pays on time or is connected to an agent for overdue accounts",
    },
    templates: [
      { title: "Upcoming due date", body: "Hi {{name}}, your {{bill_type}} of {{amount}} is due on {{date}}. Pay now: {{link}}." },
      { title: "Overdue notice", body: "Your {{bill_type}} payment of {{amount}} is overdue. Pay now to avoid late charges: {{link}}." },
    ],
    setup: [
      { step: "Register payment-reminder templates and the press-1 voice script", owner: "MsgBridge" },
      { step: "Provide the billing schedule and due-date data feed", owner: "You" },
      { step: "Set the reminder cadence: days before and after due date", owner: "You" },
      { step: "Route press-1 confirmations to your collections team", owner: "MsgBridge" },
    ],
    integration: "Feed due-date and balance data from your billing or loan-management system, and MsgBridge schedules the reminder cadence, an SMS before the date, a WhatsApp payment link, and a press-1 voice call once overdue. Payment-link clicks and press-1 confirmations post back so your collections team only chases what is genuinely unpaid.",
    metrics: ["On-time payment rate", "Reminder-to-payment conversion", "Payment-link click rate", "Press-1 connect rate on overdue accounts", "Reduction in manual collection calls"],
    faq: [
      { q: "When should the first reminder go out?", a: "A common pattern is an SMS two to three days before the due date, a reminder on the day, and an escalation once overdue. You set the exact cadence and we schedule it against your billing feed." },
      { q: "How does the press-1 voice reminder work?", a: "For overdue accounts, an automated call plays your script and lets the customer press 1 to confirm payment or connect to an agent. Confirmations route to your collections team so follow-up is targeted." },
      { q: "Can I include a payment link in the reminder?", a: "Yes. Reminders can carry a link to your payment page, and WhatsApp can deliver the link plus a receipt in one trackable thread. MsgBridge does not process the payment itself." },
      { q: "Are payment reminders treated as transactional?", a: "Reminders tied to a real obligation are service messages sent on transactional templates registered on DLT, so they reach the customer without falling foul of promotional restrictions." },
    ],
    relatedIndustries: ["/industries/bfsi", "/industries/insurance"],
    relatedProducts: ["/sms/transactional", "/voice/press-1", "/whatsapp-business-api"],
  },
  {
    slug: "/solutions/order-updates",
    name: "Order & Delivery Updates",
    problem: "Customers call to ask \"where is my order\" because the only update they got was a single email that landed in spam.",
    channels: [
      { name: "WhatsApp", why: "Order confirmed, shipped, out for delivery and delivered, all in one thread.", recommended: true },
      { name: "SMS", why: "A reliable fallback for customers without WhatsApp opted in." },
    ],
    flow: {
      trigger: "An order status changes in your logistics or order-management system",
      primary: "WhatsApp update at each status change",
      fallback: "SMS if the WhatsApp message is undelivered within 30 seconds",
      outcome: "Customer always knows where the order is, without contacting support",
    },
    templates: [
      { title: "Order shipped", body: "Your order {{order_id}} has shipped and is on its way. Track it: {{link}}." },
      { title: "Out for delivery", body: "Your order {{order_id}} is out for delivery today. {{courier_name}} will call before arrival." },
      { title: "Failed delivery attempt", body: "We tried to deliver {{order_id}} but missed you. Reschedule here: {{link}}." },
    ],
    setup: [
      { step: "Register order-lifecycle templates covering every status", owner: "MsgBridge" },
      { step: "Connect your order-management or logistics webhook to the send API", owner: "You" },
      { step: "Map each status change to the right template", owner: "You" },
      { step: "Monitor delivery reports for undelivered updates", owner: "MsgBridge" },
    ],
    integration: "Have your order-management or logistics platform post each status change to a webhook that maps the event to the right template. MsgBridge sends the update on WhatsApp with an SMS fallback, and delivery reports return so an undelivered update can retry, keeping the customer informed without a single manual touch.",
    metrics: ["Delivery rate of status updates", "Where-is-my-order support tickets deflected", "Tracking-link click rate", "Failed-delivery reschedule rate", "WhatsApp-to-SMS fallback rate"],
    faq: [
      { q: "Which order events should trigger a message?", a: "Typically order confirmed, shipped, out for delivery, delivered, and any failed-delivery attempt. Each maps to its own template so the customer gets a clear update at every stage of the journey." },
      { q: "What if the WhatsApp update is not delivered?", a: "You can configure an SMS fallback that fires when the WhatsApp message is undelivered within a short window, so the customer still gets the update on a reliable channel." },
      { q: "Can I include a live tracking link?", a: "Yes. Templates can carry a tracking link or courier details, so the customer checks status themselves instead of contacting support." },
      { q: "How does this connect to my logistics system?", a: "Your order-management or courier system calls the send API via webhook on each status change. We help map your status codes to templates during setup so no event is missed." },
    ],
    relatedIndustries: ["/industries/ecommerce", "/industries/logistics"],
    relatedProducts: ["/whatsapp-business-api", "/sms/transactional", "/rcs"],
  },
  {
    slug: "/solutions/appointments",
    name: "Appointment Reminders",
    problem: "Patients and clients forget appointments, and every no-show is an empty slot that could have gone to someone else.",
    channels: [
      { name: "SMS", why: "A simple reminder that reaches every patient, regardless of smartphone or app.", recommended: true },
      { name: "WhatsApp", why: "A reminder with a one-tap reschedule or confirm button." },
      { name: "Voice (Press-1)", why: "A call for high-value appointments where confirmation matters." },
    ],
    flow: {
      trigger: "An appointment is booked in your scheduling system",
      primary: "SMS reminder 24 hours before the appointment",
      fallback: "A second reminder 2 hours before, on WhatsApp if opted in",
      outcome: "Patient or client confirms, reschedules, or shows up on time",
    },
    templates: [
      { title: "Appointment reminder", body: "Reminder: your appointment with {{provider}} is on {{date}} at {{time}}. Reply C to confirm or R to reschedule." },
      { title: "Same-day reminder", body: "Your appointment is today at {{time}} with {{provider}} at {{location}}." },
    ],
    setup: [
      { step: "Register reminder templates for each appointment type", owner: "MsgBridge" },
      { step: "Connect your scheduling or practice-management system", owner: "You" },
      { step: "Set the reminder timing: 24 hours, 2 hours, or both", owner: "You" },
      { step: "Route confirm/reschedule replies back to your booking system", owner: "MsgBridge" },
    ],
    integration: "Connect your scheduling or practice-management system so a new booking triggers the reminder sequence automatically. MsgBridge sends the SMS and WhatsApp reminders on your timing, and confirm or reschedule replies post back to your booking system so freed slots reopen without staff re-keying anything.",
    metrics: ["No-show rate", "Reminder delivery rate", "Confirmation reply rate", "Reschedule rate via reply", "Slots recovered from cancellations"],
    faq: [
      { q: "How much does reminding reduce no-shows?", a: "Timely reminders consistently cut no-shows because most missed appointments are simply forgotten, though the exact improvement depends on your patient base and timing. A 24-hour plus same-day reminder pair usually works best." },
      { q: "Can patients confirm or reschedule by replying?", a: "Yes. Reminders can ask the patient to reply to confirm or reschedule, and on WhatsApp that can be a one-tap button. Responses route back to your scheduling system." },
      { q: "When should reminders be sent?", a: "A reminder 24 hours ahead plus a same-day nudge two hours before is a common setup. You choose the timing per appointment type and we schedule it against your bookings." },
      { q: "Do healthcare reminders keep patient data private?", a: "Templates carry only what the reminder needs, such as time, provider and location, so you avoid putting sensitive clinical detail into a message. You control exactly what each template includes." },
    ],
    relatedIndustries: ["/industries/healthcare", "/industries/education", "/industries/real-estate"],
    relatedProducts: ["/sms/transactional", "/whatsapp-business-api", "/voice/press-1"],
  },
  {
    slug: "/solutions/lead-generation",
    name: "Lead Capture & Qualification",
    problem: "Leads come in from ads and forms, then sit unanswered for hours while a competitor's faster follow-up wins the sale.",
    channels: [
      { name: "WhatsApp", why: "An instant reply the moment a lead submits a form, then a human takes over.", recommended: true },
      { name: "SMS", why: "A fast acknowledgement even before the WhatsApp conversation starts." },
      { name: "AI Chatbot", why: "Qualifies the lead with a few questions before it reaches a salesperson." },
    ],
    flow: {
      trigger: "A lead submits a form or messages from an ad",
      primary: "WhatsApp auto-reply with qualifying questions within seconds",
      fallback: "SMS acknowledgement if the lead has not opted into WhatsApp",
      outcome: "A qualified lead lands in your CRM with context, ready for follow-up",
    },
    templates: [
      { title: "Instant lead reply", body: "Hi {{name}}, thanks for your interest in {{product}}. Quick question: {{qualifying_question}}?" },
      { title: "Follow-up nudge", body: "Hi {{name}}, still interested in {{product}}? Reply YES and we'll call you today." },
    ],
    setup: [
      { step: "Register the lead-capture template and set up the chatbot flow", owner: "MsgBridge" },
      { step: "Provide qualifying questions and your CRM's lead endpoint", owner: "You" },
      { step: "Connect the ad or form source to trigger the auto-reply", owner: "You" },
      { step: "Test the handoff from bot to sales team", owner: "MsgBridge" },
    ],
    integration: "Wire your ad platform or web form to trigger an instant WhatsApp auto-reply the moment a lead submits. The chatbot asks your qualifying questions, and the enriched lead, with answers and source, is pushed to your CRM's lead endpoint so sales picks up warm, context-rich leads instead of cold form rows.",
    metrics: ["Speed to first response", "Lead reply rate", "Qualification completion rate", "Qualified-lead conversion rate", "Cost per qualified lead"],
    faq: [
      { q: "How fast can a new lead be contacted?", a: "The auto-reply is triggered the instant the form or ad submits, so the lead hears back within seconds, while intent is still high, rather than hours later when a competitor may have already responded." },
      { q: "Can the bot qualify leads before sales sees them?", a: "Yes. The chatbot asks a short set of your qualifying questions and only passes leads that meet your criteria to a salesperson, with the answers attached so the rep opens with context." },
      { q: "Does the qualified lead land in my CRM?", a: "Yes. Captured leads and their answers are posted to your CRM's lead endpoint so they appear in your pipeline automatically. Share your CRM during setup and we map the fields." },
      { q: "What if the lead has not opted into WhatsApp?", a: "An SMS acknowledgement goes out as a fallback so no lead is left without a response, and the conversation can move to WhatsApp once the lead engages." },
    ],
    relatedIndustries: ["/industries/real-estate", "/industries/education", "/industries/saas"],
    relatedProducts: ["/whatsapp-chatbot", "/whatsapp-business-api", "/sms/transactional"],
  },
  {
    slug: "/solutions/surveys",
    name: "Surveys & Feedback",
    problem: "Feedback forms sent by email get a single-digit response rate, so you make decisions without hearing from most customers.",
    channels: [
      { name: "WhatsApp", why: "A quick-reply survey inside a channel customers already check.", recommended: true },
      { name: "SMS", why: "A one-question rating survey that takes five seconds to answer." },
      { name: "Voice (Press-1)", why: "A short automated call for a single satisfaction rating." },
    ],
    flow: {
      trigger: "A purchase, support ticket, or appointment is completed",
      primary: "WhatsApp survey with quick-reply buttons sent within an hour",
      fallback: "SMS one-question rating if WhatsApp is not available",
      outcome: "Feedback lands in your dashboard, tagged to the specific interaction",
    },
    templates: [
      { title: "Post-purchase survey", body: "How was your experience with {{brand}}, {{name}}? Reply 1-5." },
      { title: "Support satisfaction check", body: "Did {{agent_name}} resolve your issue today? Reply YES or NO." },
    ],
    setup: [
      { step: "Register the survey template and set up quick-reply buttons", owner: "MsgBridge" },
      { step: "Decide which interactions trigger a survey", owner: "You" },
      { step: "Connect responses to your feedback dashboard", owner: "MsgBridge" },
      { step: "Review response trends and adjust the question set", owner: "You" },
    ],
    integration: "Trigger the survey from the moment an interaction closes, an order delivered, a ticket resolved, an appointment completed, by calling the API from that system. Responses flow back through a webhook into your feedback dashboard or CRM, tagged to the specific interaction so you know exactly what each rating is about.",
    metrics: ["Survey response rate", "Completion rate", "Average satisfaction or CSAT score", "Net promoter score", "Time from interaction to response"],
    faq: [
      { q: "Why do WhatsApp and SMS surveys respond better than email?", a: "They arrive in a channel customers already check, and quick-reply buttons or a single number reply take seconds, so more people finish. Email forms ask for more effort and often go unseen." },
      { q: "How is feedback tied to the right interaction?", a: "Each survey is triggered by a specific event and tagged with its context, so a rating maps back to the exact order, ticket or appointment, and to the agent or product involved." },
      { q: "Can I run a one-question rating?", a: "Yes. A single-question rating, such as reply 1 to 5, works well on SMS and WhatsApp and gets the highest completion. You can add follow-up questions for customers who engage." },
      { q: "Where do the responses go?", a: "Responses post to your feedback dashboard or CRM through a webhook so you can watch trends over time and act on low scores quickly. We connect this during setup." },
    ],
    relatedIndustries: ["/industries/ecommerce", "/industries/healthcare", "/industries/travel"],
    relatedProducts: ["/whatsapp-business-api", "/sms/transactional", "/voice/press-1"],
  },
];
